"""
Generate the complete NSMBW sprite database from Horizon Wiki data.
Compares against existing sprite_db.py and generates a complete update.
"""

import re

# All sprites from Horizon Wiki (extracted from the 3 pages)
# Format: (ID, Name, Notes)
# Note: HTML entities are decoded, unused/incomplete sprites marked

WIKI_SPRITES = [
    # Page 1: 0-199
    (0, "Mario Jumps! (TESTING ONLY)", ""),
    (1, "(Unused) Glitch Mario", "unused"),
    (2, "(Unused) Glitch Mario", "unused"),
    (3, "(Unused) Glitch Mario", "unused"),
    (4, "(Unused) Glitch Mario", "unused"),
    (5, "(Unused) Glitch Mario", "unused"),
    (6, "(Unused) Glitch Mario", "unused"),
    (7, "(Unused) Glitch Mario", "unused"),
    (8, "(Unused) Glitch Mario", "unused"),
    (9, "(Unused) Glitch Player Actor", "unused"),
    (10, "Unused", "unused"),
    (11, "Unused", "unused"),
    (12, "Unused", "unused"),
    (13, "Unused", "unused"),
    (14, "Unused", "unused"),
    (15, "Unused", "unused"),
    (16, "Unused", "unused"),
    (17, "Unused", "unused"),
    (18, "Unused", "unused"),
    (19, "Unused", "unused"),
    (20, "Goomba", ""),
    (21, "Paragoomba", ""),
    (22, "Unused", "unused"),
    (23, "Basic Platform - Horizontal Movement", ""),
    (24, "Buzzy Beetle", ""),
    (25, "Spiny", ""),
    (26, "Upside-Down Spiny", ""),
    (27, "Stone Block (NSMB-DS) - Vertical Movement", ""),
    (28, "Stone Block (NSMB-DS) - Horizontal Movement", ""),
    (29, "Incomplete Platform", "incomplete"),
    (30, "Grey Tiled Block", ""),
    (31, "Basic Platform - Vertical Movement", ""),
    (32, "Star Coin", ""),
    (33, "Event Controller - Zone Enter", ""),
    (34, "Event Controller - AND", ""),
    (35, "Event Controller - OR", ""),
    (36, "Event Controller - RANDOM", ""),
    (37, "Event Controller - Chainer", ""),
    (38, "Event Controller - IF", ""),
    (39, "Event Controller - Multi-Chainer", ""),
    (40, "? Switch (Orange)", ""),
    (41, "P Switch (Blue)", ""),
    (42, "! Switch (Red)", ""),
    (43, "Brick Block ? Switch (Orange)", ""),
    (44, "Brick Block P Switch (Blue)", ""),
    (45, "Brick Block ! Switch (Red)", ""),
    (46, "Lava Bubble (Podoboo)", ""),
    (47, "Thwomp", ""),
    (48, "Big Thwomp", ""),
    (49, "(Unused) Seesaw Platform", "unused"),
    (50, "Basic Platform - Fall-When-Touched", "donut block"),
    (51, "Tilt Controlled Girder", ""),
    (52, "Auto-Rotating 4-Platform", ""),
    (53, "Effect - Quicksand", ""),
    (54, "Lakitu", ""),
    (55, "(Unused) Rising Tilting Platform", "unused"),
    (56, "Rising Tilt Controlled Girder", ""),
    (57, "Koopa Troopa", ""),
    (58, "Koopa Paratroopa", ""),
    (59, "Line Controlled Tilt Girder", ""),
    (60, "Spike Top", ""),
    (61, "Big Boo", ""),
    (62, "Spinning Firebar", ""),
    (63, "Spiked Ball", ""),
    (64, "Effect - Thick Fog", ""),
    (65, "Pipe Piranha Plant - Up", ""),
    (66, "Pipe Piranha Plant - Down", ""),
    (67, "Pipe Piranha Plant - Right", ""),
    (68, "Pipe Piranha Plant - Left", ""),
    (69, "Pipe Fire Piranha Plant - Up", ""),
    (70, "Pipe Fire Piranha Plant - Down", ""),
    (71, "Pipe Fire Piranha Plant - Right", ""),
    (72, "Pipe Fire Piranha Plant - Left", ""),
    (73, "Piranha Plant", ""),
    (74, "Big Piranha Plant", ""),
    (75, "Fire Piranha Plant", ""),
    (76, "Big Fire Piranha Plant", ""),
    (77, "(Unused) Doomship Key", "unused"),
    (78, "Bouncy Cloud", ""),
    (79, "Incomplete Sprite - En Helpos", "incomplete"),
    (80, "Fire Bro", ""),
    (81, "Grey Tiled Block w/ Spikes - Left", ""),
    (82, "Grey Tiled Block w/ Spikes - Right", ""),
    (83, "Grey Tiled Block w/ Spikes - Left+Right", ""),
    (84, "Grey Tiled Block w/ Spikes - Top", ""),
    (85, "Grey Tiled Block w/ Spikes - Bottom", ""),
    (86, "Grey Tiled Block w/ Spikes - Top+Bottom", ""),
    (87, "(Unused) Trampoline Wall", "unused"),
    (88, "Incomplete Sprite - En Boyon", "incomplete"),
    (89, "Incomplete Sprite - En Remocon Torimochi", "incomplete"),
    (90, "Effect - Wind Physics and Sound", ""),
    (91, "Auto-Scrolling Controller", ""),
    (92, "Bullet Bill Launcher", ""),
    (93, "Banzai Bill Launcher", ""),
    (94, "Boomerang Bro", ""),
    (95, "Hammer Bro Plus", ""),
    (96, "Rotation Controller - Swaying", ""),
    (97, "(Unused) Rotation Controlled Block", "unused"),
    (98, "Giant Spiked Ball", ""),
    (99, "Pipe Enemy Generator", ""),
    (100, "Swoop", ""),
    (101, "Bob-Omb", ""),
    (102, "Broozer", ""),
    (103, "Basic Platform - Spawner", ""),
    (104, "Amp", ""),
    (105, "Pokey", ""),
    (106, "Line Controlled Basic Platform", ""),
    (107, "(Unused) Rotation Controlled Platform", "unused"),
    (108, "Line Controlled Amp Spawner", ""),
    (109, "Spiked Ball on a Chain", ""),
    (110, "Effect - Sunbeam", ""),
    (111, "Blooper", ""),
    (112, "Blooper Nanny with Babies", ""),
    (113, "Goal Pole and Fortress", ""),
    (114, "Burner - Continuous", ""),
    (115, "Cheep Cheep", ""),
    (116, "(Unused) Coin Cheep", "unused"),
    (117, "Burner - Pulsating", ""),
    (118, "Dry Bones", ""),
    (119, "Giant Dry Bones", ""),
    (120, "Sledge Bro", ""),
    (121, "(Crashes) Collision Switcher", ""),
    (122, "Basic Platform - One-Way", ""),
    (123, "(Unused) Swinging Castle Platform", "unused"),
    (124, "Lakitu Spawn Area", ""),
    (125, "Climbing Koopa - Horizontal", ""),
    (126, "Climbing Koopa - Vertical", ""),
    (127, "Chainlink Fence Flip Panel - Small", ""),
    (128, "Chainlink Fence Flip Panel - Long", ""),
    (129, "Paddle Wheel Platform", ""),
    (130, "Wiggler", ""),
    (131, "Boo", ""),
    (132, "(Unused) Path Controlled Platform", "unused"),
    (133, "Wobble Rock Platform", ""),
    (134, "Crowber Crow", ""),
    (135, "Unstable Hanging Chained Platform", ""),
    (136, "Rotating Bullet Bill Launcher", ""),
    (137, "Skewer - Down", ""),
    (138, "Water", ""),
    (139, "Lava", ""),
    (140, "Skewer - Up", ""),
    (141, "Skewer - Right", ""),
    (142, "Skewer - Left", ""),
    (143, "Loose Arrow", ""),
    (144, "Red Coin", ""),
    (145, "Floating Barrel", ""),
    (146, "Chain Chomp", ""),
    (147, "Coin", ""),
    (148, "Springboard", ""),
    (149, "Rotation Controller - Spinning", ""),
    (150, "(Unused) Jumping Cheep Cheep", "unused"),
    (151, "Porcu-Puffer", ""),
    (152, "Incomplete Sprite - En Blur", "incomplete"),
    (153, "(Unused) ? Switch (Orange)", "unused"),
    (154, "Porcu-Puffer Spawn Area", ""),
    (155, "Line Controlled Star Coin", ""),
    (156, "Red Coin Ring", ""),
    (157, "Big Brick Block", ""),
    (158, "Fire Snake", ""),
    (159, "Movement Controller - Uses Paths", ""),
    (160, "(Unused) Path Controlled Platform 2", "unused"),
    (161, "Pipe Bubbles", ""),
    (162, "Vertical Scroll Limiter 1 - Left", ""),
    (163, "Vertical Scroll Limiter 1 - Right", ""),
    (164, "Vertical Scroll Limiter 2 - Left", ""),
    (165, "Vertical Scroll Limiter 2 - Right", ""),
    (166, "Icy Block Train", "ice snake block"),
    (167, "Unused", "unused"),
    (168, "Unused", "unused"),
    (169, "Incomplete Sprite - En Slip Penguin", "incomplete"),
    (170, "Chestnut Goomba", ""),
    (171, "Mushroom in a Bubble", ""),
    (172, "Screw Mushroom Platform with Bolt", ""),
    (173, "Giant Floating Log", ""),
    (174, "(Unused) One Way Swinging Gate", "unused"),
    (175, "Flying ? Block", ""),
    (176, "Roulette Block", ""),
    (177, "Fire Chomp", ""),
    (178, "Basic Platform - Scale", ""),
    (179, "Special Exit Controller", ""),
    (180, "Cheep-Chomp", ""),
    (181, "Cheep Cheep Spawn - Jumping", ""),
    (182, "Event Triggered Door", ""),
    (183, "Incomplete Sprite - En TarzanRope", "incomplete"),
    (184, "Incomplete Sprite - Mask", "incomplete"),
    (185, "Ambush - Toad Balloon", ""),
    (186, "Collision Switcher - Mini-Mario Only", ""),
    (187, "Player Block", ""),
    (188, "Midway Flag", ""),
    (189, "Larry Koopa", ""),
    (190, "(Unused) Tilt Controlled Girder", "unused"),
    (191, "Tile God Event", ""),
    (192, "Larry Koopa - Castle Boss", ""),
    (193, "Urchin", ""),
    (194, "Mega Urchin", ""),
    (195, "Huckit Crab", ""),
    (196, "Fishbones", ""),
    (197, "Clampy", ""),
    (198, "Giant Goomba", ""),
    (199, "Mega Goomba", ""),
    # Page 2: 200-399
    (200, "Micro Goomba", ""),
    (201, "Icicle", ""),
    (202, "Toad House Minigame - Cannon", ""),
    (203, "Chest", ""),
    (204, "Rolling Object Spawner", ""),
    (205, "Water Ball", ""),
    (206, "Zoom Controller", ""),
    (207, "? Block", ""),
    (208, "(Unused) ? Block", "unused"),
    (209, "Brick Block", ""),
    (210, "Incomplete Sprite - Tarzan Rope", "incomplete"),
    (211, "Boss Controller - Bowser Jr (1st)", ""),
    (212, "Rolling Hill", ""),
    (213, "Incomplete Sprite - Branch", "incomplete"),
    (214, "Path Controlled Ghost House Platform", ""),
    (215, "Bullet Bill Spawn Area", ""),
    (216, "Poisoned Water", ""),
    (217, "Fire Chomp Spawn Area", ""),
    (218, "(Unused) Invisible Block", "unused"),
    (219, "Stretching Line Block", ""),
    (220, "Cheep Cheep Spawn - Swimming", ""),
    (221, "Invisible Block", ""),
    (222, "(Unused) Conveyor Belt Spike", "unused"),
    (223, "Checkered Spring Block", ""),
    (224, "Jumbo Ray", ""),
    (225, "Floating Coin", ""),
    (226, "(Unused) Water Ball", "unused"),
    (227, "Pipe Cannon", ""),
    (228, "Stretching Mushroom Platform", ""),
    (229, "Sand Pillar", ""),
    (230, "Bramball", ""),
    (231, "Wiggling Mushroom Platform", ""),
    (232, "Mecha-Koopa", ""),
    (233, "Bulber, the Glowing Fish", ""),
    (234, "Effect - Cloud Area", ""),
    (235, "Jumbo Ray Respawner", ""),
    (236, "Movement Controller - Use Lines", ""),
    (237, "Blue P-Switch Coin", ""),
    (238, "Foo, the Cloud Blower", ""),
    (239, "Incomplete Sprite - Mist Intermittent", "incomplete"),
    (240, "Big Wiggler", ""),
    (241, "(Unused) Big Wiggler Spawner", "unused"),
    (242, "Falling Ledge Bar", ""),
    (243, "(Unused) Water Current Controller", "unused"),
    (244, "Incomplete Sprite - Hana Mountain", "incomplete"),
    (245, "Incomplete Sprite - River Mgr", "incomplete"),
    (246, "Incomplete Sprite - Tag Thunder", "incomplete"),
    (247, "(Unused) Cheep Cheep Formation", "unused"),
    (248, "Horizontal Scroll Limiter - Top", ""),
    (249, "Horizontal Scroll Limiter - Bottom", ""),
    (250, "Incomplete Sprite - Kawanagare", "incomplete"),
    (251, "Incomplete Sprite - Slow Quick Tag", "incomplete"),
    (252, "Rotation Controlled Event Block", ""),
    (253, "Rotation Controlled Coin", ""),
    (254, "Rotation Controlled Pipe", "buggy"),
    (255, "Rotation Controlled ? Block", ""),
    (256, "Rotation Controlled Brick Block", ""),
    (257, "Move-When-On Lava Metal Block", ""),
    (258, "Bulber Spawn Area", ""),
    (259, "D-Pad Door", ""),
    (260, "Movement Controller - Two Way Line", ""),
    (261, "Grey Tiled Block - Two Way Line", ""),
    (262, "Poltergeist Item", ""),
    (263, "Lily Piranha Plant", ""),
    (264, "Stalking Piranha Plant", ""),
    (265, "Falling Icicle", ""),
    (266, "Rotating Chainlink Fence Wheel", ""),
    (267, "Tilt Controlled Chainlink Fence", ""),
    (268, "Lava Geyser", ""),
    (269, "Parachute Bob-Omb", ""),
    (270, "Parachute Bob-Omb Spawn Area", ""),
    (271, "Scaredy Rat", ""),
    (272, "Ice Bro", ""),
    (273, "Unused", "unused"),
    (274, "Rotation Controlled Metal Gear", ""),
    (275, "5-Enemy-Max Raft", ""),
    (276, "Ghost House Door", ""),
    (277, "Tower Boss Door", ""),
    (278, "Castle Boss Door", ""),
    (279, "Incomplete Sprite - Ac Lift Ice Spring", "incomplete"),
    (280, "Giant Ice Block", ""),
    (281, "Rising Tilt Girder Controller", ""),
    (282, "Incomplete Sprite - En WallInsect", "incomplete"),
    (283, "Incomplete Sprite - WallInsect Mgr", "incomplete"),
    (284, "Physics Coin Controller", ""),
    (285, "Rising/Falling Water", ""),
    (286, "Rotating Airship Wheel", ""),
    (287, "(Unused) Path Controlled Ice Block", "unused"),
    (288, "Rolling Barrel", ""),
    (289, "Wooden and Metal Boxes", ""),
    (290, "Incomplete Sprite - En Iwao", "incomplete"),
    (291, "Para-Beetle", ""),
    (292, "Heavy Para-Beetle", ""),
    (293, "Volcano Rock Spawn Area", ""),
    (294, "Meltable Ice Cube", ""),
    (295, "Airship Nut Platform", ""),
    (296, "Giant Buzzy Beetle", ""),
    (297, "Dragon Coaster", ""),
    (298, "Long Cannonball Cannons", ""),
    (299, "45 Degree Cannon", ""),
    (300, "4-Way Cannon", ""),
    (301, "4-Way Large Cannon with Pipe", ""),
    (302, "Loose Giant Flying Wrench", ""),
    (303, "Monty Mole", ""),
    (304, "Burner - Rotating", ""),
    (305, "Lighting - Circle", ""),
    (306, "Lighting - Rotation Spotlight", ""),
    (307, "Burner - Pulsating Sync Controller", ""),
    (308, "Platform Hammer Bro", ""),
    (309, "Burner - Pulsating Sync", ""),
    (310, "Signboard - Arrow", ""),
    (311, "Mega Icicle", ""),
    (312, "Stretching Line Block Controller", ""),
    (313, "Wiggling Mushroom Platform Ctrl", ""),
    (314, "Effect - Bubble Generator", ""),
    (315, "Movement Controller - Bolt Object", ""),
    (316, "Bolt Controlled Metal Block", ""),
    (317, "Effect - Enables Bubbles", ""),
    (318, "Box Generator", ""),
    (319, "(Unused) Wiimote Controlled Door", "unused"),
    (320, "(Unused) Sliding Wiimote Door", "unused"),
    (321, "(Unused) Beta Arrow Block", "unused"),
    (322, "Incomplete Sprite - En Ghost Jugem", "incomplete"),
    (323, "Boo Circle", ""),
    (324, "Incomplete Sprite - Ship Window", "incomplete"),
    (325, "Ghost House Stand", ""),
    (326, "King Bill", ""),
    (327, "Line Controlled Platform with Bolt", ""),
    (328, "(Unused) Bubble Cannon", "unused"),
    (329, "(Unused) Bubble Cannon Controller", "unused"),
    (330, "Rope Ladder", ""),
    (331, "Rotation Controlled Dish Platform", ""),
    (332, "Incomplete Sprite - Lift Toride Roll", "incomplete"),
    (333, "Line Controlled Player-Block Platform", ""),
    (334, "Big Cheep Cheep", ""),
    (335, "School of Cheep Cheeps", ""),
    (336, "Wendy Koopa", ""),
    (337, "Iggy Koopa", ""),
    (338, "Rising/Lowering Bullet Bill Launcher", ""),
    (339, "Moving Pipe - Facing Up", ""),
    (340, "Lemmy Koopa", ""),
    (341, "Giant Koopa Shell Cave", ""),
    (342, "Muncher", ""),
    (343, "Line Controlled Fuzzy / Big Fuzzy", ""),
    (344, "Morton Koopa", ""),
    (345, "Hanging Chain Holder", ""),
    (346, "Rotation Controlled Chain Platform", ""),
    (347, "Roy Koopa", ""),
    (348, "Ludwig von Koopa", ""),
    (349, "Morton Koopa - Castle Boss", ""),
    (350, "Incomplete Sprite - Dummy Door Parent", "incomplete"),
    (351, "Incomplete Sprite - Dummy Door Child", "incomplete"),
    (352, "Rocky Wrench", ""),
    (353, "Moving Pipe - Facing Down", ""),
    (354, "Brown Tower Block - Two Way Line", ""),
    (355, "Rolling Hill - 1 Pipe", ""),
    (356, "Brown Tower Block", ""),
    (357, "Yoshi Fruit", ""),
    (358, "Effect - Rising Lava Particle", ""),
    (359, "Lighting - Fire Lamp", ""),
    (360, "Rolling Hill - 8 Pipes", ""),
    (361, "Rotation Controlled Crystal Block", ""),
    (362, "Rotation Controlled Colored Box", ""),
    (363, "Boss Controller - Tower Boss", ""),
    (364, "Boss Controller - Roy Koopa", ""),
    (365, "Ludwig von Koopa - Castle Boss", ""),
    (366, "Rotation Controlled Mushroom Block", ""),
    (367, "Line Controlled Pink Mushroom Block", ""),
    (368, "Path Controlled Flashlight Raft", ""),
    (369, "Sliding Penguin", ""),
    (370, "Lakitu Cloud Block", ""),
    (371, "Rolling Hill Coin", ""),
    (372, "Iggy Koopa - Castle Boss", ""),
    (373, "Flashlight Raft Water", ""),
    (374, "Effect - Snow and Wind", ""),
    (375, "Wendy Koopa - Castle Boss", ""),
    (376, "Moving Chainlink Fence - Two Way", ""),
    (377, "Warp Pipe - Up", ""),
    (378, "Warp Pipe - Down", ""),
    (379, "Warp Pipe - Right", ""),
    (380, "Warp Pipe - Left", ""),
    (381, "Lemmy Koopa - Castle Boss", ""),
    (382, "Screw Mushroom Platform no Bolt", ""),
    (383, "Boss Controller - Kamek", ""),
    (384, "Sliding Penguin Generator", ""),
    (385, "Grabbable Ice Block", ""),
    (386, "POW Block", ""),
    (387, "Bush", ""),
    (388, "Barrel", ""),
    (389, "Bolt Controlled Star Coin", ""),
    (390, "Bolt Controlled Coin", ""),
    (391, "Lighting - Glow Block", ""),
    (392, "Magic Fireball Spawn Area", ""),
    (393, "Propeller Block", ""),
    (394, "Bouncing Lemmy Ball", ""),
    (395, "Spiny Cheep Cheep", ""),
    (396, "Move-When-On Platform", ""),
    (397, "Move-When-On Ghost House Box", ""),
    (398, "Long Skewer - Right", ""),
    (399, "Effect - Airship Rocking", ""),
    # Page 3: 400-482
    (400, "Long Skewer - Left", ""),
    (401, "Massive Skewer - Down", ""),
    (402, "Line Controlled ? Block", ""),
    (403, "Line Controlled Brick Block", ""),
    (404, "Massive Skewer - Up", ""),
    (405, "Boss Controller - Bowser Jr (2nd)", ""),
    (406, "Boss Controller - Bowser Jr (3rd)", ""),
    (407, "Boss Controller - Castle Boss", ""),
    (408, "Cutscene - Bowser Jr/Peach Castle", ""),
    (409, "Cutscene - Bowser Jr/Peach Airship", ""),
    (410, "Incomplete Sprite - Ac Block Group", "incomplete"),
    (411, "(Unused) Toad House Lives Balloon", "unused"),
    (412, "Toad House Minigame - Lives Balloon", ""),
    (413, "Bouncing Wendy Ring", ""),
    (414, "Spike / Stone Spike", ""),
    (415, "(Unused) Larry Koopa", "unused"),
    (416, "Invisible 1-Up - Mini-Mario Only", ""),
    (417, "Invisible Spin-Jump Coin", ""),
    (418, "Banzai Missile Bill Generator", ""),
    (419, "Bowser", ""),
    (420, "Lighting - Giant Glow Block", ""),
    (421, "(Unused) Fake Ghost House Door", "unused"),
    (422, "Toad Needs Help - ? Block", ""),
    (423, "Toad Needs Help - Brick Block", ""),
    (424, "Palm Tree", ""),
    (425, "Jellybeam", ""),
    (426, "Fireball Spawn Area", ""),
    (427, "Kamek", ""),
    (428, "Toad House Minigame - Flip Panel", ""),
    (429, "Toad House Minigame - Cannon Ctrl", ""),
    (430, "Toad House Minigame - Flip Ctrl", ""),
    (431, "Boss Controller - Bowser", ""),
    (432, "Toad NPC", ""),
    (433, "Floating ? Block", ""),
    (434, "Warp Cannon", ""),
    (435, "Effect - Ghost Fog", ""),
    (436, "Background Parallax Center Point", ""),
    (437, "Climbable Striped Pole", ""),
    (438, "Rotation Controlled Cage Blocks", ""),
    (439, "Peach in Cage - Fake", ""),
    (440, "Climbable Horizontal Rope", ""),
    (441, "Mushroom Platform", ""),
    (442, "Hint Movie Block Controller", ""),
    (443, "Hint Movie Block", ""),
    (444, "Climbable Swinging Vine - Pre-Swing", ""),
    (445, "Peach in Cage - Real", ""),
    (446, "Effect - Light Cloud Area", ""),
    (447, "Lighting - Underwater Lamp", ""),
    (448, "Metal Bar", ""),
    (449, "Bowser Fireball Spawn Area", ""),
    (450, "Enterable Warp Pipe - Up", ""),
    (451, "Scaredy Rat Despawner", ""),
    (452, "Bowser Boss Door", ""),
    (453, "Seaweed Plant", ""),
    (454, "Ambush Level Controller", ""),
    (455, "Rotation Controlled Sledge Block", ""),
    (456, "Final Boss - Bridge Pieces", ""),
    (457, "Rotation Controlled 4-Way Thin Bar", ""),
    (458, "Rotation Controlled Metal Bar", ""),
    (459, "Crowd Clapping Controller (Coin)", ""),
    (460, "Silver Gear Block - Two Way Line", ""),
    (461, "Crowd Clapping Controller 2", ""),
    (462, "Enormous Tower Block w/ Spikes", ""),
    (463, "Effect - Glare", ""),
    (464, "Climbable Swinging Vine / Chain", ""),
    (465, "Effect - Ambiance Sound Effects", ""),
    (466, "Moving Lava Glow Metal Block", ""),
    (467, "Moving Light Gem Block", ""),
    (468, "Cutscene - Credits", ""),
    (469, "Bolt Controlled Airship Platform", ""),
    (470, "Bolt Controlled Airship Wire", ""),
    (471, "Moving Pot on Bolt Platform", ""),
    (472, "Ice Floe Generator", ""),
    (473, "Floating Ice Floe Generator", ""),
    (474, "Dancing Coin/Block Controller", ""),
    (475, "Path Controlled Ice Floe", ""),
    (476, "Loose Flying Wrench", ""),
    (477, "Super Guide Block", ""),
    (478, "Bowser Switch (Small)", ""),
    (479, "Bowser Switch (Large)", ""),
    (480, "Morton's Skewer", ""),
    (481, "(Unused) Final Boss Rubble Block", "unused"),
    (482, "Final Boss - Pre-Boss Camera", ""),
]

# Generate Python constant names from sprite names
def name_to_const(name):
    """Convert a sprite name to a Python constant name."""
    # Remove notes like (Unused), (Crashes), etc.
    name = re.sub(r'\([^)]*\)', '', name)
    # Remove punctuation
    name = re.sub(r'[^\w\s]', '', name)
    # Convert to uppercase and join with underscores
    words = name.strip().split()
    return '_'.join(words).upper()

if __name__ == '__main__':
    print(f"Total sprites: {len(WIKI_SPRITES)}")
    
    # Count by category
    unused = sum(1 for _, _, n in WIKI_SPRITES if 'unused' in n)
    incomplete = sum(1 for _, _, n in WIKI_SPRITES if 'incomplete' in n)
    usable = len(WIKI_SPRITES) - unused - incomplete
    
    print(f"Usable: {usable}")
    print(f"Unused: {unused}")
    print(f"Incomplete: {incomplete}")
    
    # Show constant names for first 10
    print("\nFirst 10 constant names:")
    for id, name, notes in WIKI_SPRITES[:10]:
        const = name_to_const(name)
        print(f"  {id}: {const}  # {name}")
